"""Verify the Python port of snallabot's request-signing against vectors
generated by running their JavaScript implementation directly in node."""
from cfm.ea_client import message_auth, parse_login_redirect


def test_message_auth_vector_1():
    auth = message_auth(123456789, 1, rand4=bytes([0xDE, 0xAD, 0xBE, 0xEF]))
    assert auth["authData"] == (
        "3q2+78jHJDhdi5Gqmtsj/N3HnUCGgGEtC5qZreuPb6men4tSn8clKU2Knbqq8zO/"
        "xcyTUtGJNjZZtpzr5ItlrsvIiUeL3Co="
    )
    assert auth["authCode"] == "3DR3+ydXhk+BzHL608NXvA=="
    assert auth["authType"] == 17039361


def test_message_auth_vector_2():
    auth = message_auth(998877665544, 42, rand4=bytes([0x01, 0x02, 0x03, 0x04]))
    assert auth["authData"] == (
        "AQIDBNwTk0gBWxk7pz3xwXUvKyqSVNZdV0oRPNZpvZQ2dz04ixOSWRFaFSuXFeGC"
        "bSE7NoVTjF0aSjk8wWa8mW8tPi2RB9UJVBsN"
    )
    assert auth["authCode"] == "eqPgskaa1v4KFDQR+Sjj6w=="


def test_parse_login_redirect():
    assert parse_login_redirect(
        "http://127.0.0.1/success?code=ABC123&state=x"
    ) == "ABC123"
